# site settings
title: Janice Leun Hayes
subtitle: JANICE LEUNG writer, editor, eater, traveller
email: janiceleunghayes :at: gmail :dot: com
description: Janice Leung Hayes is an independent food writer and social entrepreneur with a deep love of food - its sources, makers, sellers and eaters.

Her written work can be found in publications such as the South China Morning Post, AFAR, New York Times, Monocle, Wall Street Journal, Australian Gourmet Traveller, Discovery Magazine (Cathay Pacific), eater.com, and more. She started her career in food writing first at a community magazine in Melbourne, then in Hong Kong at LUXE City Guides.

Under her food sustainability platform Honestly Green, in late 2015, she launched a food-focused farmers market, Tong Chong Street Market, co-presented with Swire Properties, and in 2017, Honestly Green launched Poho Market.

The markets grew from her 2012 project, Island East Markets, which was the largest urban farmers'  market in the city, and showcased artisanal products that were locally and responsibly made and grown.

For her efforts towards food sustainability, she was named "Inspiring Homegrown Entrepreneur" in the inaugural Women of Hope awards and made part of Generation T by Hong Kong Tatler.

Janice judges and contributes to major local and international food & beverage awards, lists and guides, and speaks and moderates on panels regarding the food & beverage industry, sustainability, lifestyle media and social entrepreneurship. As senior director of Little Adventures in Hong Kong, she designs and leads custom food and culture experiences.

She is a graduate of the University of Melbourne, and also holds a WSET Advanced (Level 3) Certificate, which just means she is serious about enjoying a tipple.
baseurl: "/janiceleunghayes.net" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
