# site settings
title: Janice Leung Hayes
subtitle: writer, editor, eater, traveller
email: janiceleunghayes@gmail.com
description: Janice Leung Hayes is an independent food writer and social entrepreneur with a deep love of food - its sources, makers, sellers and eaters.
baseurl: "/janiceleunghayes.net" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Janice Leung
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url: https://www.facebook.com/e.ting.food
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/e_ting/
linkedin_url: https://www.linkedin.com/in/janicektleung/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/e_ting

# build settings
markdown: kramdown

sass:
  style: compressed
